# Tensors and variables

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

import tensorflow as tf

Before we start re-implementing portions of our Keras code, we need to understand TensorFlow's basic concepts. In this notebook, we'll cover tensors and variables.

In TensorFlow, a [`Tensor`](https://www.tensorflow.org/api_docs/python/tf/Tensor) is the data structure used to store the inputs and outputs of a deep learning model. A [`Variable`](https://www.tensorflow.org/api_docs/python/tf/Variable) is a special type of tensor that is used to store any model parameters that need to be learned during training. The difference here is that tensors are immutable and variables are mutable. They're both super important concepts to understand if you're going to be working with TensorFlow.

Mathematically speaking, a tensor is just a generalization of vectors and matrices. A vector is a one-dimensional array of values, a matrix is a two-dimensional array of values, and a tensor is an array of values with any number of dimensions. A TensorFlow `Tensor`, much like NumPy's `ndarray`, gives us a way to represent multidimensional data, but with added tricks, such as the ability to perform operations on a GPU and the ability to calculate derivatives.

Suppose we want to represent this 3 &times; 2 matrix in TensorFlow:

$$
X = 
\begin{bmatrix}
  1 & 2 \\
  3 & 4 \\
  5 & 6
\end{bmatrix} 
$$

Here's the code to create the corresponding tensor:

In [2]:
X = tf.constant([[1, 2], [3, 4], [5, 6]])

We can inspect the tensor's `shape` attribute to see how many dimensions it has and the size in each dimension. The `device` attribute tells us whether the tensor is stored on the CPU or GPU, and the `dtype` attribute indicates what kind of values it holds. We use the `type` function to check the type of the tensor itself.

In [3]:
print(X.shape)
print(X.device)
print(X.dtype)
print(type(X))

(3, 2)
/job:localhost/replica:0/task:0/device:CPU:0
<dtype: 'int32'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


Note that if your machine is configured properly for TensorFlow to take advantage of a GPU, then TensorFlow will automatically decide whether to store tensors and perform tensor math on the GPU or CPU in an optimal way, without any additional work on your part.

If you've used NumPy ndarrays before, you might be happy to know that TensorFlow tensors can be indexed in a familiar way. We can slice a tensor to view a smaller portion of it:

In [4]:
X = X[0:2, 0:1]
X

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[1],
       [3]])>

We can also convert tensors to NumPy arrays by simply using the `numpy` method:

In [5]:
array = X.numpy()           
array

array([[1],
       [3]])

Variables can easily be initialized from tensors: 

In [6]:
V = tf.Variable(X)
V

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[1],
       [3]])>

As we mentioned earlier, unlike a `Tensor`, a `Variable` is mutable. We can update the value of our variable using the `assign`, `assign_add`, and `assign_sub` methods:

In [7]:
Y = tf.constant([[5], [6]])
V.assign(Y)
V

<tf.Variable 'Variable:0' shape=(2, 1) dtype=int32, numpy=
array([[5],
       [6]])>

In [8]:
V.assign_add([[1], [1]])

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=int32, numpy=
array([[6],
       [7]])>

In [9]:
V.assign_sub([[2], [2]])

<tf.Variable 'UnreadVariable' shape=(2, 1) dtype=int32, numpy=
array([[4],
       [5]])>